# Generated by Django 3.2.8 on 2021-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
