# Generated by Django 3.2.6 on 2021-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
