# Generated by Django 3.2.6 on 2021-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
