# Generated by Django 3.2.6 on 2021-11-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
        ('convert', '0004_videofiles_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='act',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='act.activity'),
        ),
    ]
