# Generated by Django 3.2.6 on 2021-11-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
        ('convert', '0005_videofiles_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='act',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='act.activity'),
        ),
    ]
