# Generated by Django 3.2.6 on 2021-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_alter_videofiles_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='a_num',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, null=True),
        ),
    ]
