# Generated by Django 3.2.6 on 2021-12-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0008_videofiles_a_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='transcript',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
