# Generated by Django 3.2.6 on 2021-12-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_alter_videofiles_transcript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofiles',
            old_name='a_num',
            new_name='activity_number',
        ),
    ]
