# Generated by Django 3.2.6 on 2021-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('convert', '0010_rename_a_num_videofiles_activity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='clss',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
