# Generated by Django 3.2.6 on 2021-12-06 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_videofiles_clss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
