# Generated by Django 3.2.6 on 2021-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0012_alter_videofiles_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='actual',
            field=models.IntegerField(null=True),
        ),
    ]
