# Generated by Django 3.2.6 on 2021-12-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0013_videofiles_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofiles',
            old_name='actual',
            new_name='accuracy',
        ),
    ]
