# Generated by Django 3.2.6 on 2021-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0014_rename_actual_videofiles_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='expected',
            field=models.IntegerField(null=True),
        ),
    ]
