# Generated by Django 3.2.6 on 2021-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100, null=True)),
                ('a_material', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
