# Generated by Django 3.2.6 on 2021-12-01 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='a_number',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
