# Generated by Django 3.2.6 on 2021-12-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_activity_a_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='expected_total',
            field=models.IntegerField(null=True),
        ),
    ]
