# Generated by Django 3.2.6 on 2021-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('act', '0003_activity_expected_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='clss',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
